---
title: "Introdução ao GGPLOT2"
output: html_document
---
date: "2024-09-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Elementos Básicos do GGPLOT2

* Carregamento das bibliotecas necessárias:

```{r}
library(dplyr)
library(ggplot2)
```

* Conjunto de dados:

```{r}
data = mtcars
head(data)
```

### Exemplo 1: Gráfico de dispersão (*Scatter Plot*)

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align = 'center'}
ggplot(data = mtcars,
       aes(
         x = mpg, y = hp
       )) +
  geom_point(aes(color=factor(cyl))) +
  labs(title = "Relação entre MPG e HP",
       x = "Milhas por Galão (mpg)",
       y = "Potência (hp)",
       color = "Cilindros (cyl)") + 
  theme_bw() +
  theme(
    legend.position = c(.99, .99),
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background=element_rect(fill = alpha("white", 0.6))
  )
```

### Exemplo 2: Gráfico de Linhas

Dados:

```{r}
TM=c(23.4,19.8,12.8,16.3,20.8,17.4,20.0,21.8,21.8,20.6,20.3,20.6,20.4,18.1,20.2,19.3,17.2,20.8,
     20.7,17.4,21.8,23.8,25.8,26.3,25.3,24.5,21.4,23.3,24.3,21.2,24.3,23.6,23.5,22.3,21.4,19.7,
     22.1,20.5,22.3,21.8,18.0,21.3,24.1,23.9,23.6,23.3,23.2,22.0,22.4,20.8,20.2,22.6,23.7,19.9,
     19.7,21.4,22.5,21.4,20.4,24.5,22.7,20.3,23.7,24.0,23.6,21.6,22.0,22.6,21.3,22.5,22.2,26.3,
     27.2,28.3,25.9,25.8,26.6,24.9,20.8,19.4,21.6,22.2,23.8,20.9,22.9,25.0,23.7,23.8,24.8,24.8,
     24.8,25.4,24.4,23.5,24.7,25.3,25.2,23.8,22.8,22.2,26.0,27.8,28.1,25.8,26.8,25.3,25.0,26.6,
     26.4,26.7,26.8,25.5,24.0,23.2,22.6,23.4,24.5,25.7,25.0,26.4,26.2,26.2,26.9,24.7,25.6,25.0,
     23.7,22.8,25.5,26.3,26.9,25.1,26.7,25.6,24.5,26.2,26.2,24.4,26.3,25.6,24.4,24.0,26.7,28.2,
     26.3,26.7,25.4,24.8,24.6,26.3,28.7,28.6,26.3,28.6,29.0,28.2,24.3,23.0,22.9,24.6,26.6,28.5,
     28.0,25.5,23.2,23.7,23.0,22.4,23.6,23.6,23.5,23.5,22.9,23.5)
UR=c(68,93,86,55,54,51,45,43,55,54,58,57,64,89,73,80,96,71,86,95,74,62,49,43,51,62,86,73,64,95,
     68,77,86,93,76,63,69,94,88,89,88,67,76,84,71,88,83,83,74,54,51,61,74,97,94,97,66,58,65,56,
     82,93,66,64,67,65,67,67,63,62,76,51,57,54,80,65,65,65,93,88,63,68,65,98,83,64,67,62,59,78,
     75,70,63,62,53,46,42,55,60,51,51,47,42,60,62,77,74,58,63,67,66,83,81,87,95,80,71,68,74,69,
     75,74,75,90,86,91,91,98,84,81,74,82,69,77,84,78,74,87,75,80,89,90,77,73,82,80,82,75,79,70,
     61,63,74,63,58,62,76,76,74,69,64,56,61,86,94,85,78,91,82,80,81,85,89,84)
TEMPO=c(1:174)

dados <- data.frame(TEMPO, TM, UR)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align = 'center'}
ggplot(data = dados,
       aes(x = TEMPO,
           y = TM)) +
  geom_line(color="steelblue", size=0.4) +
  geom_point(color="royalblue") +
  theme_bw()
```

### Exemplo 3: Gráfico de Barras

```{r}
data("starwars")
glimpse((starwars))
```
```{r}
head(starwars)
```


#### Resumo dos dados de distribuição de cores dos olhos

```{r}
starwars %>%
  group_by(eye_color) %>%
  summarise(n= n())
```

```{r}
starwars %>%
  group_by(eye_color) %>%
  summarise(n = n()) %>%
    ggplot(aes(x = n, y = eye_color)) +
  geom_bar(stat = "identity") +
  theme_bw()
```

```{r}
starwars %>%
  group_by(eye_color) %>%
  summarise(n = n()) %>%
    ggplot(aes(x = n, y = reorder(eye_color, n))) +
  geom_bar(stat = "identity") +
  theme_bw()
```

```{r}
starwars %>%
  group_by(eye_color) %>%
  summarise(n = n()) %>%
    ggplot(aes(x = n, y = reorder(eye_color, n), label = n)) +
  geom_bar(stat = "identity") +
  geom_label() +
  theme_bw()
```


```{r}
starwars %>%
  group_by(eye_color, gender) %>%
  summarise(n = n()) %>%
  ggplot(aes(x = n, y=reorder(eye_color, n), fill=gender, label=n)) +
  geom_bar(stat="identity") +
  geom_label(position="stack") +
  theme_bw()
```

